
# ---------------------------------------------------------------------------- #
# PentagonalNumberChecker.py
#
# Hey there, happy programmer! Here's a nice little ditty of a script that
# checks if a number is pentagonal. We don't need no stinkin' GUIs or fancy 
# Internet dependencies! Just good ol' fashion vanilla Python. 
# Grab a coffee, lean back, and come take a journey with me.
# ---------------------------------------------------------------------------- #

import math  # We'll use the math library for some quick maffs

def is_pentagonal(num):
    """
    Woohoo! Function Time!
    Checks if a number is pentagonal. What's a pentagonal number you ask?
    It's a number that can be represented as a pentagon, where the amount of dots 
    on each edge are the number input. In mathematical terms,
    each pentagonal number is generated by the formula Pn=n(3n−1)/2 for n
    being the nth pentagonal number. Let's give it a whirl!

    :param num: The number to check. But you already knew that, didn't ya? 😉
    :return: True if the number is pentagonal, False if it's not. Easy peasy!
    """
    test_num = (math.sqrt(24 * num + 1) + 1) / 6  # Rearranging the pentagonal number formula like a BOSS!

    # If test_num is a whole number, our input is a pentagonal number!
    # We're using the modulus operator to check if there's no remainder
    # when divided by 1. Because math. 💪
    return test_num.is_integer()

def main():
    """
    And now we reach the main function. The bread and butter. The masterpiece.
    Where all the magic happens. Wait no further, let's step in!
    """
    # Let's get that number from the user.
    # And remember, we don't judge here in this friendly CLI environment.
    # Any number is welcome! 😊
    num = int(input('Enter a number to check if it is a pentagonal: '))

    # Invoke our wonderful little function to check if the number is pentagonal
    # and store the outcome (True or False). Isn't Python neat?
    result = is_pentagonal(num)

    # Let's share the results with our wonderful user. Drumroll, please...
    if result:
        print(f'Yup Yup! The number {num} is pentagonal. Score!')
    else:
        print(f'Darn! The number {num} is not pentagonal. Better luck next time!')

# Time for our script to take the stage!
# If we're being run as a script, fire up our main function.
if __name__ == "__main__":
    main()

# And there you have it - a neat, simple little script.
# Just remember - you're awesome, and your code is too.
# Cheers, and happy coding! 🎉
